apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../resources

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: azuredevops-data-ws
    - op: replace
      path: /data/AZP_POOL
      value: Windows-Self-Hosted-Data-WE
  target:
    kind: ConfigMap
    name: azuredevops
- patch: |-
    - op: replace
      path: /metadata/name
      value: agentcleaner-data-ws
  target:
    kind: CronJob
    name: agentcleaner
- patch: |-
    - op: replace
      path: /metadata/name
      value: azuredevops-deployment-data-ws
    - op: replace
      path: /spec/selector/matchLabels/app.kubernetes.io~1name
      value: azuredevops-data-ws
    - op: replace
      path: /spec/template/metadata/labels/app.kubernetes.io~1name
      value: azuredevops-data-ws
    - op: replace
      path: /spec/template/spec/volumes/0/csi/volumeAttributes/secretProviderClass
      value: azuredevops-token-data-ws
    - op: add
      path: /spec/template/metadata/labels/azure.workload.identity~1use
      value: "true"
    - op: add
      path: /spec/template/spec/serviceAccountName
      value: wi-agents-azdevops-sa
    # - op: remove
    #   path: /spec/template/spec/containers/0/env/0
    # - op: remove
    #   path: /spec/template/spec/containers/0/volumeMounts/0
    # - op: remove
    #   path: /spec/template/spec/volumes/0
  target:
    kind: Deployment
    name: azuredevops-deployment
- patch: |-
    - op: replace
      path: /metadata/name
      value: pipeline-trigger-auth-data-ws
  target:
    kind: TriggerAuthentication
    name: pipeline-trigger-auth
- patch: |-
    - op: replace
      path: /metadata/name
      value: azure-pipelines-scaledobject-data-ws
    - op: replace
      path: /spec/scaleTargetRef/name
      value: azuredevops-deployment-data-ws
    - op: replace
      path: /spec/triggers/0/metadata/poolName
      value: Windows-Self-Hosted-Data-WE
    - op: replace
      path: /spec/triggers/0/authenticationRef/name
      value: pipeline-trigger-auth-data-ws
  target:
    kind: ScaledObject
    name: azure-pipelines-scaledobject
- patch: |-
    - op: replace
      path: /metadata/name
      value: azuredevops-token-data-ws
  target:
    kind: SecretProviderClass
    name: azuredevops-token

images:
- name: agent
  newName: myacr.azurecr.io/azure/devops-agent-dataws
  newTag: "202501295"
