---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  labels:
    app.kubernetes.io/name: azuredevops-token
  name: azuredevops-token
spec:
  provider: azure
  secretObjects:
    - secretName: azuredevops
      type: Opaque
      data:
        - objectName: azuredevops-pat
          key: AZP_TOKEN
        - objectName: azuredevops-client
          key: AZP_CLIENT_ID
        - objectName: azuredevops-tenant
          key: AZP_TENANT_ID
        - objectName: azuredevops-secret
          key: AZP_SECRET_VALUE
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: #myuserassignedidentityid
    keyvaultName: #mykeyvault
    objects: |
      array:
        - |
          objectName: azuredevops-pat
          objectType: secret
        - |
          objectName: azuredevops-client
          objectType: secret
        - |
          objectName: azuredevops-tenant
          objectType: secret
        - |
          objectName: azuredevops-secret
          objectType: secret
    tenantId: #mytenantid
