FROM ubuntu:focal AS main

LABEL maintainer="jorgepezuela"

#########
#DEFAULT#
#########
# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

######
#BASE#
######
# **********************************************
# Set common components
# **********************************************
RUN apt-get update \
  && apt-get install --no-install-recommends \
  apt-utils \
  build-essential \
  curl \
  ca-certificates \
  gnupg \
  git \
  gpg \
  jq \
  libncurses5-dev \
  libgdbm-dev \
  libnss3-dev \
  libssl-dev \
  libreadline-dev \
  libffi-dev \
  libsqlite3-dev \
  libbz2-dev \
  make \
  openjdk-17-jdk \
  python-openssl \
  software-properties-common \
  unzip \
  wget \
  zlib1g-dev

# **********************************************
# Install libicu library
# **********************************************
RUN curl http://ftp.debian.org/debian/pool/main/i/icu/libicu63_63.1-6+deb10u3_amd64.deb \
  --output libicu63_63.1-6+deb10u3_amd64.deb && dpkg -i libicu63_63.1-6+deb10u3_amd64.deb

FROM main AS agent

# **********************************************
# Install Powershell and Kubectl
# **********************************************
RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb \
    && apt-get update && export DEBIAN_FRONTEND=noninteractive

RUN echo "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg]  https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list \
  && curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg \
  && apt-get update

RUN apt-get install --no-install-recommends \
  powershell kubectl \
  && rm -rf /var/lib/apt/lists/*

# **********************************************
# Install azcli components
# **********************************************
RUN curl -LsS https://aka.ms/InstallAzureCLIDeb | bash \
  && rm -rf /var/lib/apt/lists/*

# **********************************************
# Install kustomize
# **********************************************
RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
RUN mv /kustomize /usr/local/bin/kustomize

WORKDIR /azp

# **********************************************
# Install Python Versions
# **********************************************
ADD https://www.python.org/ftp/python/3.7.14/Python-3.7.14.tgz Python-3.7.14.tgz

RUN bash -c 'mkdir -p /azp/_work/_tool/Python/3.7.14/{x64,x64.complete}'

RUN tar xvzf Python-3.7.14.tgz
RUN rm -f /azp/Python-3.7.14.tgz

RUN cd /azp/Python-3.7.14 && ./configure --enable-optimizations && ./configure --prefix=/azp/_work/_tool/Python/3.7.14/x64/ && make && make install

# Crea un enlace simbólico desde python a python3
RUN ln -s /azp/_work/_tool/Python/3.7.14/x64/bin/python3.7 /azp/_work/_tool/Python/3.7.14/x64/bin/python & \
  ln -s /azp/_work/_tool/Python/3.7.14/x64/bin/pip3 /azp/_work/_tool/Python/3.7.14/x64/bin/pip

RUN rm -rf /azp/Python-3.7.14


##############
#AGENT & USER#
##############
# **********************************************
# Install AzureDevops Scripts
# **********************************************
ADD start-data.sh /start-data.sh
RUN chmod +x /start-data.sh

ADD stop.sh /stop.sh
RUN chmod +x /stop.sh

# **********************************************
# Create user noroot
# **********************************************
RUN groupadd -g 1001 azp && \
  useradd -r -u 1001 -g azp -d /azp azp

RUN chown -R azp:azp /azp

USER azp

# **********************************************
# Install azpwsh components
# **********************************************
RUN pwsh -Command Install-Module -Name Az.Accounts, Az.ApiManagement -Repository PSGallery -Scope CurrentUser -Force

# **********************************************
# Entrypoint
# **********************************************
ENTRYPOINT ["/start-data.sh"]
