FROM mcr.microsoft.com/windows/servercore:ltsc2022

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# **********************************************
# Install PowerShell 7
# **********************************************

RUN Invoke-WebRequest -Uri "https://github.com/PowerShell/PowerShell/releases/download/v7.4.1/PowerShell-7.4.1-win-x64.msi" -OutFile "C:\Users\ContainerAdministrator\AppData\Local\Temp\PowerShell.msi" -UseBasicParsing ; \
    msiexec.exe /package C:\Users\ContainerAdministrator\AppData\Local\Temp\PowerShell.msi /quiet ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL=1 ADD_FILE_CONTEXT_MENU_RUNPOWERSHELL=1 ENABLE_PSREMOTING=1 REGISTER_MANIFEST=1 USE_MU=1 ENABLE_MU=1 ADD_PATH=1; \
	Remove-Item -Path 'C:\Users\ContainerAdministrator\AppData\Local\Temp\PowerShell.msi' -Force

# **********************************************
# Instalación de Git
# **********************************************

RUN Invoke-WebRequest -Uri 'https://github.com/git-for-windows/git/releases/download/v2.35.1.windows.1/Git-2.35.1-64-bit.exe' -OutFile 'C:\Users\ContainerAdministrator\AppData\Local\Temp\git-installer.exe' -UseBasicParsing ; \
    Start-Process -FilePath 'C:\Users\ContainerAdministrator\AppData\Local\Temp\git-installer.exe' -ArgumentList '/VERYSILENT /NORESTART /NOCANCEL /SP-' -Wait ; \
    Remove-Item -Path 'C:\Users\ContainerAdministrator\AppData\Local\Temp\git-installer.exe' -Force

# **********************************************
# Install .NET Core SDK 6 & 8 for CI
# **********************************************

RUN Invoke-WebRequest -UseBasicParsing -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1; \
    ./dotnet-install.ps1 -InstallDir 'C:\Program Files\dotnet' -Channel 6.0 -Runtime dotnet; \
    ./dotnet-install.ps1 -InstallDir 'C:\Program Files\dotnet' -Channel 8.0 -Runtime dotnet; \
    Remove-Item -Force dotnet-install.ps1; \
    [Environment]::SetEnvironmentVariable('PATH', $Env:PATH + ';C:\Program Files\dotnet', [EnvironmentVariableTarget]::Machine)
# Installation: "C:\Users\ContainerAdministrator\AppData\Local\Microsoft\dotnet\"

# **********************************************
# Install Visual C++ 2022
# **********************************************

RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
	Invoke-WebRequest "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "C:\Users\ContainerAdministrator\AppData\Local\Temp\vc_redist.x64.exe"; \
	Start-Process -filepath C:\Users\ContainerAdministrator\AppData\Local\Temp\vc_redist.x64.exe -ArgumentList "/install", "/passive", "/norestart" -Passthru | Wait-Process; \
	Remove-Item -Path 'C:\Users\ContainerAdministrator\AppData\Local\Temp\vc_redist.x64.exe'-Force

# **********************************************
# Install Visual Studio Tools
# **********************************************

# Download the Build Tools bootstrapper.
RUN Invoke-WebRequest -Uri "https://aka.ms/vs/16/release/vs_buildtools.exe" -OutFile 'C:\Users\ContainerAdministrator\AppData\Local\Temp\vs_buildtools.exe'; \
# Install Build Tools excluding workloads and components with known issues.
    Start-Process -FilePath 'C:\Users\ContainerAdministrator\AppData\Local\Temp\vs_buildtools.exe' -ArgumentList '--quiet', '--norestart', '--nocache', \
    '--installPath C:\\BuildTools', \
    '--add Microsoft.VisualStudio.Workload.AzureBuildTools', \
    '--remove Microsoft.VisualStudio.Component.Windows10SDK.10240', \
    '--remove Microsoft.VisualStudio.Component.Windows10SDK.10586', \
    '--remove Microsoft.VisualStudio.Component.Windows10SDK.14393', \
    '--remove Microsoft.VisualStudio.Component.Windows81SDK' -NoNewWindow -Wait; \
    Remove-Item -Path 'C:\Users\ContainerAdministrator\AppData\Local\Temp\vs_buildtools.exe' -Force

# **********************************************
# Install choco
# **********************************************

RUN Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
# Allow installing without asking:
RUN choco feature enable -n allowGlobalConfirmation

# **********************************************
# Install choco Componets
# **********************************************

# Java SE Development kit 11 (open source):
RUN choco install openjdk11 -y;
# Java SE Development kit 17 (open source):
RUN choco install openjdk17 -y;
# Java 8:
RUN choco install jdk8;
# refreshenv ¿?

# Microsoft Edge
RUN choco install microsoft-edge -y

# Optional:
# RUN choco install git -y;
# RUN choco install osquery --version 5.5.1 -y;

# **********************************************
# Descargar e instalar Microsoft Edge WebView2 Runtime
# **********************************************

RUN Invoke-WebRequest -Uri 'https://go.microsoft.com/fwlink/p/?LinkId=2124703' -OutFile 'WebView2Runtime.exe' -UseBasicParsing ; \
    Start-Process -FilePath 'WebView2Runtime.exe' -ArgumentList '/silent /install' -Wait ; \
    Remove-Item -Path 'WebView2Runtime.exe' -Force


# **********************************************
# Install Microsoft System CLR Types for SQL Server 2019
# **********************************************
RUN Invoke-WebRequest -Uri 'https://download.microsoft.com/download/4/3/2/4320347c-cd8d-4caf-bc5f-07de366076fd/SQLSysClrTypes.msi' -OutFile "C:\Users\ContainerAdministrator\AppData\Local\Temp\SQLSysClrTypes.msi" -UseBasicParsing; \
    msiexec /i "C:\Users\ContainerAdministrator\AppData\Local\Temp\SQLSysClrTypes.msi" /quiet /norestart

# **********************************************
# Azure Devops Agents
# **********************************************

WORKDIR /azp
COPY start.ps1 .
COPY stop.ps1 .

CMD ["powershell", ".\\start.ps1"]

# Define the entry point for the docker container.
# This entry point starts the developer command prompt and launches the PowerShell shell.
# SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
# ENTRYPOINT ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]
# ENTRYPOINT ["powershell", ".\\start.ps1"]
