FROM ubuntu:focal AS main

LABEL maintainer="jorgepezuela"

# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

# **********************************************
# Set common components
# **********************************************
RUN apt-get update \
  && apt-get install --no-install-recommends \
  apt-utils \
  build-essential \
  curl \
  ca-certificates \
  git \
  gpg \
  jq \
  libncurses5-dev \
  libgdbm-dev \
  libnss3-dev \
  libssl-dev \
  libreadline-dev \
  libffi-dev \
  libsqlite3-dev \
  libbz2-dev \
  make \
  openjdk-11-jdk \
  python-openssl \
  software-properties-common \
  unzip \
  wget \
  zlib1g-dev

# **********************************************
# Install libicu library
# **********************************************
RUN curl http://ftp.debian.org/debian/pool/main/i/icu/libicu63_63.1-6+deb10u3_amd64.deb \
  --output libicu63_63.1-6+deb10u3_amd64.deb && dpkg -i libicu63_63.1-6+deb10u3_amd64.deb

FROM main AS agent

# **********************************************
# Install azcli components
# **********************************************
RUN curl -LsS https://aka.ms/InstallAzureCLIDeb | bash \
  && rm -rf /var/lib/apt/lists/*

# **********************************************
# Install dotnet components and kubernetes repo
# **********************************************
RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb  \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb \
    && apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get  install --no-install-recommends dotnet-runtime-6.0

RUN echo "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg]  https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list \
  && curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg \
  && apt-get update

# **********************************************
# Install Powershell and Kubectl
# **********************************************
RUN apt-get install --no-install-recommends \
  powershell kubectl \
  && rm -rf /var/lib/apt/lists/*

# **********************************************
# Install kustomize
# **********************************************
RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
RUN mv /kustomize /usr/local/bin/kustomize

WORKDIR /azp

# **********************************************
# Install Brew
# **********************************************
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
ENV PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"

# **********************************************
# Install Python Versions
# **********************************************
ADD https://www.python.org/ftp/python/3.10.13/Python-3.10.13.tgz Python-3.10.13.tgz

RUN bash -c 'mkdir -p /azp/_work/_tool/Python/3.10.13/{x64,x64.complete}'

RUN tar xvzf Python-3.10.13.tgz
RUN rm -f /azp/Python-3.10.13.tgz

RUN cd /azp/Python-3.10.13 && ./configure --enable-optimizations && ./configure --prefix=/azp/_work/_tool/Python/3.10.13/x64/ && make && make install

#Create a symlink from python to python3 as recomended in PEP394(https://peps.python.org/pep-0394/) to avoid issues when running python
RUN ln -s /azp/_work/_tool/Python/3.10.13/x64/bin/python3.10 /azp/_work/_tool/Python/3.10.13/x64/bin/python & \
  ln -s /azp/_work/_tool/Python/3.10.13/x64/bin/pip3 /azp/_work/_tool/Python/3.10.13/x64/bin/pip

RUN rm -rf /azp/Python-3.10.13

# **********************************************
# Install Datadog-ci, NVM & NODEJS
# **********************************************

# Install npm
RUN apt-get update \
  && apt-get install npm --no-install-recommends

# Install datadog-ci
RUN npm install -g @datadog/datadog-ci

# # Set environment variables 
# ENV NVM_DIR="/azp/.nvm"
# ENV NODE_VERSION=23
# ENV PATH "$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH"

# #  Install nvm
# RUN curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh" | sh 

# Install node version 23
RUN apt-get update \
&& apt-get install ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& NODE_MAJOR=23 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
&& apt-get update \
&& apt-get install nodejs  \
# && npm install -g @angular/cli \
&& npm install -g npm@latest

# **********************************************
# Install AzureDevops Scripts
# **********************************************
ADD start.sh /start.sh
RUN chmod +x /start.sh

ADD stop.sh /stop.sh
RUN chmod +x /stop.sh

RUN groupadd -g 1001 azp && \
  useradd -r -u 1001 -g azp -d /azp azp

RUN chown -R azp:azp /home/linuxbrew/.linuxbrew/Homebrew /home/linuxbrew/.linuxbrew/Cellar /home/linuxbrew/.linuxbrew/bin \
 /home/linuxbrew/.linuxbrew/etc /home/linuxbrew/.linuxbrew/etc/bash_completion.d /home/linuxbrew/.linuxbrew/include \
 /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/opt /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/share \
 /home/linuxbrew/.linuxbrew/share/doc /home/linuxbrew/.linuxbrew/share/man /home/linuxbrew/.linuxbrew/share/man/man1 \
 /home/linuxbrew/.linuxbrew/share/zsh /home/linuxbrew/.linuxbrew/share/zsh/site-functions /home/linuxbrew/.linuxbrew/var/homebrew/linked \
 /home/linuxbrew/.linuxbrew/var/homebrew/locks
RUN chown -R azp:azp /azp

USER azp

# **********************************************
# Entrypoint
# **********************************************
ENTRYPOINT ["/start.sh"]
